/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.hamigua;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.view.View;
import android.view.Window;
import android.view.animation.Animation;
import android.view.animation.TranslateAnimation;
import android.widget.TextView;

import com.hamigua.utils.SharedPreferencesUtils;
import com.hamigua.view.GestureLockView;
import com.hamigua.view.GestureLockView.OnGestureFinishListener;

public class PwdSetting extends Activity {
    private Animation animation;
    private GestureLockView gestureLockView;
    private String key;
    private String pwd;
    private String temp;
    private TextView textview;
    private TextView tv;
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        setContentView(R.layout.activity_enterapp);
        init();
    }
    
    public void init()
	{
		gestureLockView=(GestureLockView)findViewById(R.id.gestureLockView);
		textview=(TextView)findViewById(R.id.textview);
		animation = new TranslateAnimation(-20, 20, 0, 0);
		animation.setDuration(50);
		animation.setRepeatCount(2);
		animation.setRepeatMode(Animation.REVERSE);
		//设置密码
		gestureLockView.setKey("063");
		//手势完成后回调
		gestureLockView.setOnGestureFinishListener(new OnGestureFinishListener() {
			@Override
			public void OnGestureFinish(boolean success, String key) {
				if(success)
				{
					textview.setTextColor(Color.parseColor("#FFFFFF"));
					textview.setVisibility(View.VISIBLE);
					textview.setText("密码正确！");
					textview.startAnimation(animation);
				}
				else
				{
					textview.setTextColor(Color.parseColor("#FF2525"));
					textview.setVisibility(View.VISIBLE);
					textview.setText("密码错误！");
					textview.startAnimation(animation);
				}
			}
		});
	}
}

