/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.hamigua.dao;

import java.util.ArrayList;
import java.util.List;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.content.ContentValues;
import android.database.Cursor;

public class ApplockDao {
    private Applockinfodb helper;
    
    public ApplockDao(Context context) {
        helper = new Applockinfodb(context);
    }
    
    public void addlock(String packname) {
        SQLiteDatabase db = helper.getWritableDatabase();
        ContentValues values = new ContentValues();
        values.put("packname", packname);
        db.insert("lockinfo", null, values);
        db.close();
    }
    
    public void delete(String packname) {
        SQLiteDatabase db = helper.getWritableDatabase();
        db.delete("lockinfo", "packname=?", new String[] {packname});
        db.close();
    }
    
    public boolean find(String packname) {
        boolean flag = false;
        SQLiteDatabase db = helper.getReadableDatabase();
        Cursor cursor = db.query("lockinfo", null, "packname=?", new String[] {packname}, null, null, null);
        if(cursor.moveToNext()) {
            flag = true;
        }
        cursor.close();
        db.close();
        return flag;
    }
    /**
	 * 查询全部的包名
	 * @param packname
	 * @return
	 */
	public List<String> findAll(){
		List<String> protectPacknames = new ArrayList<String>();
		SQLiteDatabase db = helper.getReadableDatabase();
		Cursor cursor = db.query("lockinfo", new String[]{"packname"}, null,null, null, null, null);
		while(cursor.moveToNext()){
			protectPacknames.add(cursor.getString(0));
		}
		cursor.close();
		db.close();
		return protectPacknames;
	}
}
