/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.hamigua.dao;

import android.database.sqlite.SQLiteOpenHelper;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

public class Applockinfodb extends SQLiteOpenHelper {
    
    public Applockinfodb(Context context) {
        super(context, "applockinfo", null, 1);
    }
    
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("create table lockinfo(packname varchar(100))");
    }
    
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
    }
}
